name: Caller workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: CanarysPlayground/actions-demo/.github/workflows/main.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - run: |
          echo Add other actions to build,
          echo test, and deploy your project.
